name: Build and deploy Node.js app to Azure Web App - nodebb-f24

on:
  push:
    branches:
      - f24
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    uses: ./.github/workflows/test.yaml

  build-and-deploy:
    if: github.repository == 'bluesleep313/nodebb-f24-bluesleep'
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: List files for debugging
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: npm install
        working-directory: ./install

      - name: Set up NodeBB
        run: |
          ./nodebb setup '{"url":"https://nodebb-f24.azurewebsites.net:443",
            "admin:username": "admin",
            "admin:password": "${{ secrets.ADMIN_PASSWORD }}",
            "admin:password:confirm": "${{ secrets.ADMIN_PASSWORD }}",
            "admin:email": "rohanpadhye@cmu.edu",
            "database": "redis",
            "redis:host": "${{ secrets.REDIS_HOST }}",
            "redis:port": "6379",
            "redis:password": "${{ secrets.REDIS_PASSWORD }}" }'
        working-directory: ./install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'team-bluesleep-db'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BFAB97B1AB1441ACA7C63280F91AD3F3 }}
          package: ./install
